// Type definitions for composite types and helper interfaces
// Definitions by Dan Reed <https://danreed.dev>

/** @todo Complete this list. Any FrameMaker object. */
type FMObject = null;

/** @todo Complete this list. Any FrameMaker graphic object. */
type FMGraphic = null;

/** @todo Complete this list. Any CMS object. */
type CMSObject = null;

/** Constants that represent Notification types. */
type FA_Note = Constants.FA_Note_AI_Supported_File | Constants.FA_Note_Alert | Constants.FA_Note_AssignId | Constants.FA_Note_BackToUser | Constants.FA_Note_BodyPageAdded | Constants.FA_Note_BodyPageDeleted | Constants.FA_Note_CMS_PostCheckOutItem | Constants.FA_Note_CMS_PostOpenItem | Constants.FA_Note_CMS_PreCheckOutItem | Constants.FA_Note_CMS_PreOpenItem |
	Constants.FA_Note_ClientCall | Constants.FA_Note_ConsoleMessage | Constants.FA_Note_CursorChange | Constants.FA_Note_DITAOptions | Constants.FA_Note_Dialog | Constants.FA_Note_Dialog_Create | Constants.FA_Note_DirtyBook | Constants.FA_Note_DirtyDoc | Constants.FA_Note_DisplayClientTiDialog | Constants.FA_Note_DisplayClientXRefDialog |
	Constants.FA_Note_ECMInternal | Constants.FA_Note_Enable_Disable_DITA_Menu_Commands | Constants.FA_Note_EnumeratedComponent | Constants.FA_Note_FileOpen | Constants.FA_Note_FilterFileToFile | Constants.FA_Note_FilterIn | Constants.FA_Note_FilterOut | Constants.FA_Note_FontSubstitution | Constants.FA_Note_Frame_Idle_State | Constants.FA_Note_GenerateFM |
	Constants.FA_Note_GraphicPropChanged | Constants.FA_Note_Help | Constants.FA_Note_HtmlNotify | Constants.FA_Note_In_App_Message | Constants.FA_Note_InsertConRef | Constants.FA_Note_InsertTopicRef | Constants.FA_Note_IsCommandEnabled | Constants.FA_Note_LoadKeyCatalog | Constants.FA_Note_MATHML_CHANGE_NSPREFIX | Constants.FA_Note_MATHML_CHANGE_XML_PROPERTY |
	Constants.FA_Note_MATHML_DblClicked | Constants.FA_Note_MATHML_Deselected | Constants.FA_Note_MATHML_GenerateImage | Constants.FA_Note_MATHML_PopulateObj | Constants.FA_Note_MATHML_Selected | Constants.FA_Note_NewBookmapFile | Constants.FA_Note_NewConceptFile | Constants.FA_Note_NewDitamapFile | Constants.FA_Note_NewGlossEntryFile | Constants.FA_Note_NewReferenceFile |
	Constants.FA_Note_NewTaskFile | Constants.FA_Note_NewTopicFile | Constants.FA_Note_Not_AI_Supported_File | Constants.FA_Note_Not_RSC_Supported_File | Constants.FA_Note_Not_SWF_File | Constants.FA_Note_Not_U3DCommand | Constants.FA_Note_Num | Constants.FA_Note_OpenAllTopicrefs | Constants.FA_Note_Open_Dtd | Constants.FA_Note_Open_EDD_For_App |
	Constants.FA_Note_Open_Schema | Constants.FA_Note_Palette | Constants.FA_Note_PostActiveDocChange | Constants.FA_Note_PostAutoSaveDoc | Constants.FA_Note_PostBookComponentOpen | Constants.FA_Note_PostChangeElement | Constants.FA_Note_PostCopyElement | Constants.FA_Note_PostCreateMML | Constants.FA_Note_PostDistill | Constants.FA_Note_PostDragElement |
	Constants.FA_Note_PostExport | Constants.FA_Note_PostFileType | Constants.FA_Note_PostFunction | Constants.FA_Note_PostGenerate | Constants.FA_Note_PostGoToXrefSrc | Constants.FA_Note_PostHypertext | Constants.FA_Note_PostImport | Constants.FA_Note_PostImportElemDefs | Constants.FA_Note_PostInlineTypeIn | Constants.FA_Note_PostInsertElement |
	Constants.FA_Note_PostMouseCommand | Constants.FA_Note_PostOpenBook | Constants.FA_Note_PostOpenBookMIF | Constants.FA_Note_PostOpenDoc | Constants.FA_Note_PostOpenMIF | Constants.FA_Note_PostOpenSGML | Constants.FA_Note_PostOpenXML | Constants.FA_Note_PostPrint | Constants.FA_Note_PostPublishDitamap | Constants.FA_Note_PostQuitBook |
	Constants.FA_Note_PostQuitDoc | Constants.FA_Note_PostQuitSession | Constants.FA_Note_PostRevertBook | Constants.FA_Note_PostRevertDoc | Constants.FA_Note_PostSaveAsPDFDialog | Constants.FA_Note_PostSaveBook | Constants.FA_Note_PostSaveBookMIF | Constants.FA_Note_PostSaveDoc | Constants.FA_Note_PostSaveMIF | Constants.FA_Note_PostSaveSGML |
	Constants.FA_Note_PostSaveXML | Constants.FA_Note_PostSetAttrValue | Constants.FA_Note_PostSetPropertyValue | Constants.FA_Note_PostSwitchView | Constants.FA_Note_PostUpdateXRefs | Constants.FA_Note_PostWrapElement | Constants.FA_Note_Poster_Applied | Constants.FA_Note_PreAutoSaveDoc | Constants.FA_Note_PreBookComponentOpen | Constants.FA_Note_PreChangeElement |
	Constants.FA_Note_PreCopyElement | Constants.FA_Note_PreCreateMML | Constants.FA_Note_PreDistill | Constants.FA_Note_PreDragElement | Constants.FA_Note_PreExport | Constants.FA_Note_PreFileType | Constants.FA_Note_PreFunction | Constants.FA_Note_PreGenerate | Constants.FA_Note_PreGoToXrefSrc | Constants.FA_Note_PreHypertext |
	Constants.FA_Note_PreImport | Constants.FA_Note_PreImportElemDefs | Constants.FA_Note_PreInlineTypeIn | Constants.FA_Note_PreInsertElement | Constants.FA_Note_PreMouseCommand | Constants.FA_Note_PreOpenBook | Constants.FA_Note_PreOpenBookMIF | Constants.FA_Note_PreOpenDoc | Constants.FA_Note_PreOpenMIF | Constants.FA_Note_PreOpenSGML |
	Constants.FA_Note_PreOpenXML | Constants.FA_Note_PrePrint | Constants.FA_Note_PrePublishDitamap | Constants.FA_Note_PreQuitBook | Constants.FA_Note_PreQuitDoc | Constants.FA_Note_PreQuitSession | Constants.FA_Note_PreRevertBook | Constants.FA_Note_PreRevertDoc | Constants.FA_Note_PreSaveAsPDFDialog | Constants.FA_Note_PreSaveBook |
	Constants.FA_Note_PreSaveBookMIF | Constants.FA_Note_PreSaveDoc | Constants.FA_Note_PreSaveMIF | Constants.FA_Note_PreSaveSGML | Constants.FA_Note_PreSaveXML | Constants.FA_Note_PreSetAttrValue | Constants.FA_Note_PreSetPropertyValue | Constants.FA_Note_PreSwitchView | Constants.FA_Note_PreUpdateXRefs | Constants.FA_Note_PreWrapElement |
	Constants.FA_Note_QuitModelessDialog | Constants.FA_Note_RSC_Supported_File | Constants.FA_Note_RTL_NumberUtility | Constants.FA_Note_ReLoadKeyCatalog | Constants.FA_Note_Read_Struct_App | Constants.FA_Note_Reset_Client_State | Constants.FA_Note_SWF_File | Constants.FA_Note_SetAttrValue | Constants.FA_Note_SetUniqueAttr | Constants.FA_Note_Struct_Wizard |
	Constants.FA_Note_ToolBar | Constants.FA_Note_U3DCommand | Constants.FA_Note_URL | Constants.FA_Note_UndoCheckpoint | Constants.FA_Note_UpdateAllClientTi | Constants.FA_Note_UpdateClientTi | Constants.FA_Note_UpdateDITAReference | Constants.FA_Note_UpdateDITAReferences | Constants.FA_Note_UpdateRefs | Constants.FA_Note_UpdateRefs_On_Save |
	Constants.FA_Note_WelcomeScreen_Command;

/** Constants that represent FMObject types. */
type FO_Constant = Constants.FO_Session | Constants.FO_StringResource | Constants.FO_Book | Constants.FO_BookComponent | Constants.FO_Doc | Constants.FO_BodyPage | Constants.FO_MasterPage | Constants.FO_RefPage | Constants.FO_HiddenPage | Constants.FO_UnanchoredFrame |
	Constants.FO_Group | Constants.FO_Arc | Constants.FO_Rectangle | Constants.FO_Ellipse | Constants.FO_RoundRect | Constants.FO_Polyline | Constants.FO_Polygon | Constants.FO_Line | Constants.FO_TextLine | Constants.FO_TextFrame |
	Constants.FO_Inset | Constants.FO_Math | Constants.FO_DBGroup | Constants.FO_AFrame | Constants.FO_Marker | Constants.FO_Fn | Constants.FO_XRef | Constants.FO_XRefFmt | Constants.FO_Var | Constants.FO_VarFmt |
	Constants.FO_Flow | Constants.FO_Pgf | Constants.FO_PgfFmt | Constants.FO_CharFmt | Constants.FO_CondFmt | Constants.FO_Color | Constants.FO_Tbl | Constants.FO_TblFmt | Constants.FO_Row | Constants.FO_Cell |
	Constants.FO_RulingFmt | Constants.FO_ElementDef | Constants.FO_Element | Constants.FO_DialogResource | Constants.FO_DlgBox | Constants.FO_DlgButton | Constants.FO_DlgTriBox | Constants.FO_DlgCheckBox | Constants.FO_DlgPopUp | Constants.FO_DlgScrollBox |
	Constants.FO_DlgEditBox | Constants.FO_DlgRadioButton | Constants.FO_DlgLabel | Constants.FO_DlgImage | Constants.FO_DlgScrollBar | Constants.FO_Menu | Constants.FO_Command | Constants.FO_MenuItemSeparator | Constants.FO_FmtChangeList | Constants.FO_FmtRule |
	Constants.FO_FmtRuleClause | Constants.FO_TiFlow | Constants.FO_TiText | Constants.FO_TiTextTable | Constants.FO_TiApiClient | Constants.FO_SubCol | Constants.FO_MarkerType | Constants.FO_CombinedFontDefn | Constants.FO_Rubi | Constants.FO_Alert |
	Constants.FO_CursorResource | Constants.FO_AttrCondExpr | Constants.FO_DlgListView | Constants.FO_GraphicsFmt | Constants.FO_CMSRegistration | Constants.FO_CMSSession | Constants.FO_CMSObject | Constants.FO_KeyCatalog | Constants.FO_Iterator | Constants.FO_MathML |
	Constants.FO_DlgDate | Constants.FO_InlineComponent | Constants.FO_Column | Constants.FO_Page | Constants.FO_Graphic | Constants.FO_Frame | Constants.FO_Cblock | Constants.FO_SubCond | Constants.FO_SubStyle | Constants.FO_SubDash |
	Constants.FO_SubCell | Constants.FO_SubTbl | Constants.FO_SubPblock | Constants.FO_SubTextDef | Constants.FO_MenuCell | Constants.FO_TextInset | Constants.FO_DitaMap | Constants.FO_Last_Internal | Constants.FO_CMSConnection | Constants.FO_CMSObject2 |
	Constants.FO_Bad;

/** Constants that represent FM property types. */
type FP_Constant = Constants.FP_AFrameIsCropped | Constants.FP_AFrameIsFloating | Constants.FP_AcrobatBookmarkDisplayTags | Constants.FP_AcrobatLevel | Constants.FP_ActiveAlert | Constants.FP_ActiveBook | Constants.FP_ActiveCMSSession | Constants.FP_ActiveDoc | Constants.FP_ActiveView |
	Constants.FP_AddMarkerTypeToStandardMarkers | Constants.FP_AdjHyphens | Constants.FP_AlertClientName | Constants.FP_AlertClientUnique | Constants.FP_AlertString | Constants.FP_AlertType | Constants.FP_Alignment | Constants.FP_AllowAsSpecialCase | Constants.FP_AllowBaseFamilyBoldedAndObliqued | Constants.FP_AllowNewFileURL |
	Constants.FP_AllowedDataRange | Constants.FP_AlsoInsert | Constants.FP_AlsoInserts | Constants.FP_AnchorType | Constants.FP_Angle | Constants.FP_ApplyEOPRules | Constants.FP_ApplyFormatRules | Constants.FP_ArrowBaseAngle | Constants.FP_ArrowLength | Constants.FP_ArrowScaleFactor |
	Constants.FP_ArrowScaleHead | Constants.FP_ArrowTipAngle | Constants.FP_ArrowType | Constants.FP_AsianComposer | Constants.FP_AttrCondExprIsActive | Constants.FP_AttrCondExprStr | Constants.FP_AttrDisplay | Constants.FP_AttributeDefs | Constants.FP_AttributeValueInvalid | Constants.FP_AttributeValueRequired |
	Constants.FP_Attributes | Constants.FP_AttributesEx | Constants.FP_AutoBackup | Constants.FP_AutoChangeBars | Constants.FP_AutoNumChar | Constants.FP_AutoNumString | Constants.FP_AutoSave | Constants.FP_AutoSaveSeconds | Constants.FP_BIBGetAddressProc | Constants.FP_BannerText |
	Constants.FP_BannerTextDisplay | Constants.FP_BaseFamily | Constants.FP_BasePointX | Constants.FP_BasePointY | Constants.FP_BaselineOffset | Constants.FP_BkColor | Constants.FP_BkGndColor | Constants.FP_Black | Constants.FP_BlockLines | Constants.FP_BookComponent |
	Constants.FP_BookComponentFileType | Constants.FP_BookComponentIsFolderWithTemplate | Constants.FP_BookComponentIsFolderWithoutTemplate | Constants.FP_BookComponentIsGeneratable | Constants.FP_BookComponentMissing | Constants.FP_BookComponentParent | Constants.FP_BookComponentSequenceLevel | Constants.FP_BookComponentTemplatePath | Constants.FP_BookComponentTitle | Constants.FP_BookComponentType |
	Constants.FP_BookDontUpdateReferences | Constants.FP_BookIsModified | Constants.FP_BookIsSelected | Constants.FP_BookIsViewOnly | Constants.FP_BookParent | Constants.FP_BooleanConditionExpression | Constants.FP_BooleanConditionExpressionTag | Constants.FP_BooleanConditionState | Constants.FP_BorderWidth | Constants.FP_BottomMargin |
	Constants.FP_BottomRowSelection | Constants.FP_BottomSepAtIndent | Constants.FP_BottomSeparator | Constants.FP_Box_BG_Color | Constants.FP_CMSItemProperty_ItemCheckedOutByCurrentUser | Constants.FP_CMSItemProperty_ItemFileType | Constants.FP_CMSItemProperty_ItemIsCheckedOut | Constants.FP_CMSItemProperty_ItemIsContainer | Constants.FP_CMSItemProperty_ItemLocalPath | Constants.FP_CMSItemProperty_ItemName |
	Constants.FP_CMSItemProperty_ItemServerPath | Constants.FP_CMSItemProperty_ItemType | Constants.FP_CMSItemProperty_ItemVersion | Constants.FP_CMSItemProperty_Max | Constants.FP_CMSItemProperty_Min | Constants.FP_CMSObjectLocalPath | Constants.FP_CMSObjectServerURL | Constants.FP_CTFontContext | Constants.FP_CanHaveCheckMark | Constants.FP_Capitalization |
	Constants.FP_CellAboveInCol | Constants.FP_CellAngle | Constants.FP_CellBelowInCol | Constants.FP_CellBelowInTbl | Constants.FP_CellBottomMargin | Constants.FP_CellBottomMarginChange | Constants.FP_CellBottomMarginFixed | Constants.FP_CellColNum | Constants.FP_CellColumn | Constants.FP_CellDefaultBottomRuling |
	Constants.FP_CellDefaultLeftRuling | Constants.FP_CellDefaultRightRuling | Constants.FP_CellDefaultTopRuling | Constants.FP_CellIsShown | Constants.FP_CellIsStraddled | Constants.FP_CellLeftMargin | Constants.FP_CellLeftMarginChange | Constants.FP_CellLeftMarginFixed | Constants.FP_CellMarginSpacingDelta | Constants.FP_CellMarginsFixed |
	Constants.FP_CellNumColsStraddled | Constants.FP_CellNumRowsStraddled | Constants.FP_CellOverrideBottomRuling | Constants.FP_CellOverrideFill | Constants.FP_CellOverrideLeftRuling | Constants.FP_CellOverrideRightRuling | Constants.FP_CellOverrideShading | Constants.FP_CellOverrideTopRuling | Constants.FP_CellRightMargin | Constants.FP_CellRightMarginChange |
	Constants.FP_CellRightMarginFixed | Constants.FP_CellRow | Constants.FP_CellTopMargin | Constants.FP_CellTopMarginChange | Constants.FP_CellTopMarginFixed | Constants.FP_CellUseOverrideBRuling | Constants.FP_CellUseOverrideFill | Constants.FP_CellUseOverrideLRuling | Constants.FP_CellUseOverrideRRuling | Constants.FP_CellUseOverrideShading |
	Constants.FP_CellUseOverrideTRuling | Constants.FP_CellVAlignment | Constants.FP_ChangeBar | Constants.FP_ChangeBarColor | Constants.FP_ChangeBarDistance | Constants.FP_ChangeBarPosition | Constants.FP_ChangeBarThickness | Constants.FP_ChapNumComputeMethod | Constants.FP_ChapterNumStyle | Constants.FP_ChapterNumText |
	Constants.FP_ChapterNumber | Constants.FP_CharTag | Constants.FP_CharacterReferencesOnXMLExport | Constants.FP_CheckMarkIsOn | Constants.FP_ColGap | Constants.FP_ColGapWidth | Constants.FP_Color | Constants.FP_ColorOverprint | Constants.FP_ColorPrintCtl | Constants.FP_ColorTintPercent |
	Constants.FP_ColorViewCtl | Constants.FP_ColumnIsShown | Constants.FP_ColumnNum | Constants.FP_ColumnTbl | Constants.FP_ColumnsAreBalanced | Constants.FP_CombinedFontFamily | Constants.FP_CommandNum | Constants.FP_Comment | Constants.FP_ComponentDisplayText | Constants.FP_ComponentElement |
	Constants.FP_ComponentIsDitaMap | Constants.FP_ComponentIsSelected | Constants.FP_ComponentType | Constants.FP_CondFmtIsShown | Constants.FP_ContentHeight | Constants.FP_ContentIsLooselyValid | Constants.FP_ContentIsStrictlyValid | Constants.FP_ContentMustBeEmpty | Constants.FP_ContentNeededAtBegin | Constants.FP_ContentNeededAtEnd |
	Constants.FP_ContextForCSS | Constants.FP_ContextLabel | Constants.FP_CorrespondingXmlPath | Constants.FP_CountElements | Constants.FP_CurrentDoc | Constants.FP_CurrentInset | Constants.FP_CurrentMenuSet | Constants.FP_CurrentPage | Constants.FP_CursorData | Constants.FP_CursorTypes |
	Constants.FP_CustomDelimiter | Constants.FP_CustomDocPath | Constants.FP_CustomElementList | Constants.FP_Cyan | Constants.FP_DTheta | Constants.FP_Dash | Constants.FP_Day | Constants.FP_DbAttributes | Constants.FP_DbCancelButton | Constants.FP_DbCheckBoxState |
	Constants.FP_DbDefaultButton | Constants.FP_DbEditable | Constants.FP_DbFbCurrentDir | Constants.FP_DbFbScrollBox | Constants.FP_DbFbStatus | Constants.FP_DbFbTextBox | Constants.FP_DbFirstFocus | Constants.FP_DbIdentifier | Constants.FP_DbItemNum | Constants.FP_DbNoHelp |
	Constants.FP_DbOKButton | Constants.FP_DbRadioButtonGroup | Constants.FP_DbSbxNumLines | Constants.FP_DbStuffItem | Constants.FP_DbTitleLabel | Constants.FP_DbType | Constants.FP_DbVarLabelWidth | Constants.FP_DefaultExclusions | Constants.FP_DefaultFontAngle | Constants.FP_DefaultFontFamily |
	Constants.FP_DefaultFontVariation | Constants.FP_DefaultFontWeight | Constants.FP_DefaultInclusions | Constants.FP_DefaultKeyCatalog | Constants.FP_DefaultVectorFormatForXMLExport | Constants.FP_Description | Constants.FP_DescriptiveTag | Constants.FP_DesktopHeight | Constants.FP_DesktopWidth | Constants.FP_DesktopX |
	Constants.FP_DesktopY | Constants.FP_DialogEncodingName | Constants.FP_Dictionary | Constants.FP_DirectOLESupportInXml | Constants.FP_Direction | Constants.FP_DisableAutofitAfterZoom | Constants.FP_DisplayName | Constants.FP_Displaying | Constants.FP_DitaMaxRefLevels | Constants.FP_DitaMode |
	Constants.FP_DoNotExportInvalidXML | Constants.FP_DoNotGenerateErrorLog | Constants.FP_DoPostXSLTValidationOnExport | Constants.FP_DocAcrobatColumnArticleThreads | Constants.FP_DocAcrobatDefaultsChanged | Constants.FP_DocAcrobatElementList | Constants.FP_DocAcrobatElements | Constants.FP_DocAcrobatNoArticleThreads | Constants.FP_DocCMSType | Constants.FP_DocFluidFlow |
	Constants.FP_DocFonts | Constants.FP_DocInTempState | Constants.FP_DocIsDoubleSided | Constants.FP_DocIsHelp | Constants.FP_DocIsInternal | Constants.FP_DocIsModified | Constants.FP_DocIsSave | Constants.FP_DocIsStructuredDummy | Constants.FP_DocIsUIOpen | Constants.FP_DocIsViewOnly |
	Constants.FP_DocIsViewOnlyWinPalette | Constants.FP_DocOpenClientEncounteredErrors | Constants.FP_DocOpenType | Constants.FP_DocSaveFormat | Constants.FP_DocSaveType | Constants.FP_DocSequenceLevel | Constants.FP_DockDialog | Constants.FP_DontLoadStartupClients | Constants.FP_DontShowWelcomeScreen | Constants.FP_DontUpdateTextInsets |
	Constants.FP_DontUpdateXRefs | Constants.FP_DoubleClick | Constants.FP_DownloadFonts | Constants.FP_EddUpdateOn | Constants.FP_ElemPrefixSuffix | Constants.FP_Element | Constants.FP_ElementBoundaryDisplay | Constants.FP_ElementCatalog | Constants.FP_ElementCatalogDisplay | Constants.FP_ElementDataType |
	Constants.FP_ElementDef | Constants.FP_ElementDefType | Constants.FP_ElementDescription | Constants.FP_ElementInCatalog | Constants.FP_ElementIsCollapsed | Constants.FP_ElementIsExcludedInContext | Constants.FP_ElementIsInvalidInParent | Constants.FP_ElementIsInvalidInPosition | Constants.FP_ElementIsTopicGroup | Constants.FP_ElementIsTopicHead |
	Constants.FP_ElementIsTopicRef | Constants.FP_ElementIsUndefined | Constants.FP_ElementMarkedForNamedDestination | Constants.FP_ElementPgfFormat | Constants.FP_ElementSelection | Constants.FP_ElementType | Constants.FP_ElementTypeMismatch | Constants.FP_EnableAutoSpellCheck | Constants.FP_EnabledWhen | Constants.FP_EqnIntegralSizeLarge |
	Constants.FP_EqnIntegralSizeMed | Constants.FP_EqnIntegralSizeSmall | Constants.FP_EqnLevel1SizeLarge | Constants.FP_EqnLevel1SizeMed | Constants.FP_EqnLevel1SizeSmall | Constants.FP_EqnLevel2SizeLarge | Constants.FP_EqnLevel2SizeMed | Constants.FP_EqnLevel2SizeSmall | Constants.FP_EqnLevel3SizeLarge | Constants.FP_EqnLevel3SizeMed |
	Constants.FP_EqnLevel3SizeSmall | Constants.FP_EqnSigmaSizeLarge | Constants.FP_EqnSigmaSizeMed | Constants.FP_EqnSigmaSizeSmall | Constants.FP_ErrorInBookComponent | Constants.FP_ExcludeBookComponent | Constants.FP_Exclusions | Constants.FP_ExpandOMaticParent | Constants.FP_ExportFilters | Constants.FP_ExtractElementTags |
	Constants.FP_ExtractTags | Constants.FP_FMConsoleString | Constants.FP_FMInterfaceEncodingName | Constants.FP_FM_BinDir | Constants.FP_FM_CurrentDir | Constants.FP_FM_HelpDir | Constants.FP_FM_HomeDir | Constants.FP_FM_InitDir | Constants.FP_FM_SgmlDir | Constants.FP_FM_StructureDir |
	Constants.FP_FM_XmlDir | Constants.FP_FamilyName | Constants.FP_Fcode | Constants.FP_Fcodes | Constants.FP_FileExtensionOverride | Constants.FP_FileInfoPacket | Constants.FP_FileOpenInProgress | Constants.FP_Fill | Constants.FP_FirstAFrame | Constants.FP_FirstAttrCondExprInDoc |
	Constants.FP_FirstBodyPageInDoc | Constants.FP_FirstCell | Constants.FP_FirstCellInRow | Constants.FP_FirstCharFmtInDoc | Constants.FP_FirstChildElement | Constants.FP_FirstColorInDoc | Constants.FP_FirstColumnInSelection | Constants.FP_FirstColumnInTbl | Constants.FP_FirstCombinedFontDefnInDoc | Constants.FP_FirstCommandInSession |
	Constants.FP_FirstComponentInBook | Constants.FP_FirstComponentInBookComponent | Constants.FP_FirstCondFmtInDoc | Constants.FP_FirstDITAConrefElementInDoc | Constants.FP_FirstDITALinkElementInDoc | Constants.FP_FirstDITATopicrefElementInDoc | Constants.FP_FirstDITATopicsetrefElementInDoc | Constants.FP_FirstDITAXrefElementInDoc | Constants.FP_FirstElementDefInDoc | Constants.FP_FirstFlowInDoc |
	Constants.FP_FirstFmtChangeListInDoc | Constants.FP_FirstFn | Constants.FP_FirstFnInDoc | Constants.FP_FirstGraphicInDoc | Constants.FP_FirstGraphicInFrame | Constants.FP_FirstGraphicInGroup | Constants.FP_FirstGraphicsFmtInDoc | Constants.FP_FirstIndent | Constants.FP_FirstIndentChange | Constants.FP_FirstIndentIsRelative |
	Constants.FP_FirstIndentRelPos | Constants.FP_FirstInlineComponentInDoc | Constants.FP_FirstKeyCatalogInSession | Constants.FP_FirstMarkerInDoc | Constants.FP_FirstMarkerTypeInDoc | Constants.FP_FirstMasterPageInDoc | Constants.FP_FirstMenuItemInMenu | Constants.FP_FirstMenuItemInSession | Constants.FP_FirstOpenBook | Constants.FP_FirstOpenDoc |
	Constants.FP_FirstPageNum | Constants.FP_FirstPageVerso | Constants.FP_FirstPgf | Constants.FP_FirstPgfFmtInDoc | Constants.FP_FirstPgfInDoc | Constants.FP_FirstPgfRules | Constants.FP_FirstRefPageInDoc | Constants.FP_FirstRowInTbl | Constants.FP_FirstRubiInDoc | Constants.FP_FirstRulingFmtInDoc |
	Constants.FP_FirstSelectedComponentInBook | Constants.FP_FirstSelectedGraphicInDoc | Constants.FP_FirstSelectedTiInDoc | Constants.FP_FirstSubCol | Constants.FP_FirstTblFmtInDoc | Constants.FP_FirstTblInDoc | Constants.FP_FirstTextFrameInFlow | Constants.FP_FirstTiInDoc | Constants.FP_FirstVarFmtInDoc | Constants.FP_FirstVarInDoc |
	Constants.FP_FirstVis | Constants.FP_FirstVisibleColumnInTbl | Constants.FP_FirstXRefFmtInDoc | Constants.FP_FirstXRefInDoc | Constants.FP_Flow | Constants.FP_FlowIsAutoConnect | Constants.FP_FlowIsFeathered | Constants.FP_FlowIsPostScript | Constants.FP_FlowIsSynchronized | Constants.FP_Fmt |
	Constants.FP_FmtChangeList | Constants.FP_FmtChangeListInCatalog | Constants.FP_FmtChangeListTag | Constants.FP_FmtRule | Constants.FP_FmtRuleClause | Constants.FP_FmtRuleClauses | Constants.FP_FmtRuleType | Constants.FP_FnAnchorString | Constants.FP_FnCustNumString | Constants.FP_FnFirstNum |
	Constants.FP_FnFmt | Constants.FP_FnHeightPerCol | Constants.FP_FnInstancePosition | Constants.FP_FnInstancePrefix | Constants.FP_FnInstanceSuffix | Constants.FP_FnNum | Constants.FP_FnNumComputeMethod | Constants.FP_FnNumStyle | Constants.FP_FnNumberingPerPage | Constants.FP_FnRefPosition |
	Constants.FP_FnRefPrefix | Constants.FP_FnRefSuffix | Constants.FP_Focus | Constants.FP_FontAngle | Constants.FP_FontAngleNames | Constants.FP_FontEncodingName | Constants.FP_FontFamily | Constants.FP_FontFamilyAttributes | Constants.FP_FontFamilyFullNames | Constants.FP_FontFamilyNames |
	Constants.FP_FontPanoseName | Constants.FP_FontPlatformName | Constants.FP_FontPostScriptName | Constants.FP_FontSize | Constants.FP_FontSizeChange | Constants.FP_FontVariation | Constants.FP_FontVariationNames | Constants.FP_FontWeight | Constants.FP_FontWeightNames | Constants.FP_FormViewConfigFile |
	Constants.FP_FormatOverride | Constants.FP_FormatTag | Constants.FP_FormattingLocked | Constants.FP_FrameParent | Constants.FP_Functions | Constants.FP_GeneralRule | Constants.FP_GeneralRuleErrorOffsets | Constants.FP_GenerateAcrobatInfo | Constants.FP_GenerateInclude | Constants.FP_GraphicCantBeSelected |
	Constants.FP_GraphicIsButton | Constants.FP_GraphicIsSelected | Constants.FP_Gravity | Constants.FP_GreekSize | Constants.FP_GroupDialog | Constants.FP_GroupParent | Constants.FP_HasShiftOrUnshiftCommand | Constants.FP_HeadArrow | Constants.FP_Height | Constants.FP_HelpLink |
	Constants.FP_HelpPending | Constants.FP_HiddenPage | Constants.FP_HighestLevelElement | Constants.FP_HoleAtEnd | Constants.FP_HoleBeforeElement | Constants.FP_HorizontalSpreadLarge | Constants.FP_HorizontalSpreadMed | Constants.FP_HorizontalSpreadSmall | Constants.FP_HostName | Constants.FP_HotspotCmdStr |
	Constants.FP_HotspotTitle | Constants.FP_Hypertext | Constants.FP_HypertextCommandText | Constants.FP_HypertextDoValidate | Constants.FP_HypertextParseBadParam | Constants.FP_HypertextParseErr | Constants.FP_HypertextParseErrMsg | Constants.FP_HypertextParsedArgs | Constants.FP_HypertextParsedClientName | Constants.FP_HypertextParsedCmdCode |
	Constants.FP_HypertextParsedCmdDest | Constants.FP_HypertextParsedCmdDestObjID | Constants.FP_HypertextParsedCmdDestObjType | Constants.FP_HypertextParsedCmdMatrixColumns | Constants.FP_HypertextParsedCmdMatrixRows | Constants.FP_HypertextParsedDIFileName | Constants.FP_HypertextParsedFlowName | Constants.FP_HypertextParsedLinkName | Constants.FP_HypertextParsedMessage | Constants.FP_HypertextParsedPageName |
	Constants.FP_HypertextParsedRangeName | Constants.FP_HypertextParsedTitle | Constants.FP_HypertextValidateErr | Constants.FP_HyphMinPrefix | Constants.FP_HyphMinSuffix | Constants.FP_HyphMinWord | Constants.FP_Hyphenate | Constants.FP_IDAttrValue | Constants.FP_INSETinfo | Constants.FP_Icon |
	Constants.FP_IconBarOn | Constants.FP_IconColorPref | Constants.FP_IconSizePref | Constants.FP_ImportFilters | Constants.FP_ImportFmtInclude | Constants.FP_ImportHint | Constants.FP_InCond | Constants.FP_InTableSortOperation | Constants.FP_InTextFrame | Constants.FP_InTextObj |
	Constants.FP_Inclusions | Constants.FP_IncrVal | Constants.FP_InitStructurePattern | Constants.FP_InkName | Constants.FP_InlineComponentType | Constants.FP_InsertLinks | Constants.FP_InsetCuePointList | Constants.FP_InsetDpi | Constants.FP_InsetEditor | Constants.FP_InsetFile |
	Constants.FP_InsetFileOrigName | Constants.FP_InsetGenericData | Constants.FP_InsetGfxActiveInPdf | Constants.FP_InsetGfxName | Constants.FP_InsetGfxPlayWindowInPdf | Constants.FP_InsetIsFixedSize | Constants.FP_InsetIsFlippedSideways | Constants.FP_InsetIsInverted | Constants.FP_InsetJavaScriptAttached | Constants.FP_InsetJavaScriptFile |
	Constants.FP_InsetLinkToText | Constants.FP_InsetMonikerFilePath | Constants.FP_InsetMonikerPath | Constants.FP_InsetPosterFile | Constants.FP_InsetPosterFileOrigName | Constants.FP_InsetPosterIsExternal | Constants.FP_InsetRasterDpi | Constants.FP_InsetSaveDIBFacetToFile | Constants.FP_InsetSaveFacetToFile | Constants.FP_InsetU3dAnimationList |
	Constants.FP_InsetU3dPartList | Constants.FP_InsetU3dViewList | Constants.FP_InsetURL | Constants.FP_InsetUpdater | Constants.FP_InternalAlignment | Constants.FP_InternalAnchorType | Constants.FP_InternalBaselineOffset | Constants.FP_InternalHeight | Constants.FP_InternalMathMLApplyPgfStyle | Constants.FP_InternalMathMLComposeDpi |
	Constants.FP_InternalMathMLDpi | Constants.FP_InternalMathMLFontSize | Constants.FP_InternalMathMLInline | Constants.FP_InternalMathMLXmlData | Constants.FP_InternalWidth | Constants.FP_InvalidHighestLevel | Constants.FP_InvariantName | Constants.FP_IsDefault | Constants.FP_IsDialogDocked | Constants.FP_IsDialogVisible |
	Constants.FP_IsDitamapInResourceManager | Constants.FP_IsDocDita | Constants.FP_IsDocDitamap | Constants.FP_IsFMRunningAsServer | Constants.FP_IsFMRunningInTrialPeriod | Constants.FP_IsFateRun | Constants.FP_IsFormViewEnabled | Constants.FP_IsHotspot | Constants.FP_IsIconified | Constants.FP_IsInFront |
	Constants.FP_IsOnScreen | Constants.FP_IsRestoring | Constants.FP_IsStale | Constants.FP_IsTechnicalSuiteLicensed | Constants.FP_IsTempOpenSave | Constants.FP_IsTextRange | Constants.FP_KByteAllocationSize | Constants.FP_KeepWithNext | Constants.FP_KeepWithPrev | Constants.FP_KernX |
	Constants.FP_KernY | Constants.FP_KeyCatalog | Constants.FP_KeyCatalogClientName | Constants.FP_KeyCatalogType | Constants.FP_KeyCatalogWorkflow | Constants.FP_KeyCount | Constants.FP_KeyboardShortcutLabel | Constants.FP_KeyboardShortcuts | Constants.FP_Label | Constants.FP_LabelBold |
	Constants.FP_LabelColor | Constants.FP_Labels | Constants.FP_Language | Constants.FP_LastAFrame | Constants.FP_LastBodyPageInDoc | Constants.FP_LastCell | Constants.FP_LastChildElement | Constants.FP_LastColumnInSelection | Constants.FP_LastColumnInTbl | Constants.FP_LastFn |
	Constants.FP_LastGraphicInFrame | Constants.FP_LastGraphicInGroup | Constants.FP_LastMasterPageInDoc | Constants.FP_LastPgf | Constants.FP_LastPgfRules | Constants.FP_LastRefPageInDoc | Constants.FP_LastRowInTbl | Constants.FP_LastSubCol | Constants.FP_LastTextFrameInFlow | Constants.FP_LastUpdate |
	Constants.FP_LastVisibleColumnInTbl | Constants.FP_Leading | Constants.FP_LeadingChange | Constants.FP_LeftColNum | Constants.FP_LeftIndent | Constants.FP_LeftIndentChange | Constants.FP_LeftMargin | Constants.FP_LeftMasterPage | Constants.FP_LetterSpace | Constants.FP_LineAscent |
	Constants.FP_LineBaseline | Constants.FP_LineBreakAfter | Constants.FP_LineCap | Constants.FP_LineDescent | Constants.FP_LineNumColor | Constants.FP_LineNumDistance | Constants.FP_LineNumFont | Constants.FP_LineNumRestart | Constants.FP_LineNumShow | Constants.FP_LineNumSize |
	Constants.FP_LineSpacing | Constants.FP_LineSpacingFactor | Constants.FP_LineSpacingFixed | Constants.FP_LoadStartupScripts | Constants.FP_LocX | Constants.FP_LocY | Constants.FP_Locked | Constants.FP_LogMissingFontsWarning | Constants.FP_Magenta | Constants.FP_MagicMarker |
	Constants.FP_MainFlowInDoc | Constants.FP_MarkerNames | Constants.FP_MarkerText | Constants.FP_MarkerTypeId | Constants.FP_MarkerTypeNames | Constants.FP_MasterPage | Constants.FP_MatchesContextInUserString | Constants.FP_MatchingFirstPgfClauses | Constants.FP_MatchingLastPgfClauses | Constants.FP_MatchingObjectClauses |
	Constants.FP_MatchingPrefixClauses | Constants.FP_MatchingSuffixClauses | Constants.FP_MatchingTextClauses | Constants.FP_MathFullForm | Constants.FP_MathMLApplyPgfStyle | Constants.FP_MathMLComposeDpi | Constants.FP_MathMLData | Constants.FP_MathMLDpi | Constants.FP_MathMLExportEntitiesAsValues | Constants.FP_MathMLFile |
	Constants.FP_MathMLFontSize | Constants.FP_MathMLImportGraphicsDpi | Constants.FP_MathMLInline | Constants.FP_MathMLIsFixedSize | Constants.FP_MathMLIsFlippedSideways | Constants.FP_MathMLIsInverted | Constants.FP_MathMLNamespacePrefix | Constants.FP_MathMLXmlData | Constants.FP_MathSize | Constants.FP_MaxBottomMargin |
	Constants.FP_MaxFirstIndent | Constants.FP_MaxFontSize | Constants.FP_MaxInterPgfPadding | Constants.FP_MaxInterlinePadding | Constants.FP_MaxJLetSpace | Constants.FP_MaxJRomSpace | Constants.FP_MaxLeading | Constants.FP_MaxLeftIndent | Constants.FP_MaxLeftMargin | Constants.FP_MaxRightIndent |
	Constants.FP_MaxRightMargin | Constants.FP_MaxSize | Constants.FP_MaxSpace | Constants.FP_MaxSpaceAbove | Constants.FP_MaxSpaceBelow | Constants.FP_MaxSpread | Constants.FP_MaxStretch | Constants.FP_MaxTabPosition | Constants.FP_MaxTopMargin | Constants.FP_MaxVal |
	Constants.FP_MenuBar | Constants.FP_MenuItemIsEnabled | Constants.FP_MenuItemType | Constants.FP_MenuType | Constants.FP_Mif8bitOutput | Constants.FP_MifFileEntity | Constants.FP_MifFileName | Constants.FP_MifFileOrigFormat | Constants.FP_MinBottomMargin | Constants.FP_MinFirstIndent |
	Constants.FP_MinFontSize | Constants.FP_MinHang | Constants.FP_MinJLetSpace | Constants.FP_MinJRomSpace | Constants.FP_MinLeading | Constants.FP_MinLeftIndent | Constants.FP_MinLeftMargin | Constants.FP_MinRightIndent | Constants.FP_MinRightMargin | Constants.FP_MinSize |
	Constants.FP_MinSpace | Constants.FP_MinSpaceAbove | Constants.FP_MinSpaceBelow | Constants.FP_MinSpread | Constants.FP_MinStretch | Constants.FP_MinTabPosition | Constants.FP_MinTopMargin | Constants.FP_MinVal | Constants.FP_Mode | Constants.FP_ModelessDialogUpdate |
	Constants.FP_ModelessDlgIconN | Constants.FP_ModelessDlgIconR | Constants.FP_Month | Constants.FP_MoveTabs | Constants.FP_Name | Constants.FP_Namespace | Constants.FP_NamespaceScope | Constants.FP_NarrowRubiSpaceForJapanese | Constants.FP_NarrowRubiSpaceForOther | Constants.FP_NewElemAttrDisplay |
	Constants.FP_NewElemAttrEditing | Constants.FP_NextAFrame | Constants.FP_NextAttrCondExprInDoc | Constants.FP_NextBookComponentInDFSOrder | Constants.FP_NextCell | Constants.FP_NextCellInRow | Constants.FP_NextCellInTbl | Constants.FP_NextCharFmtInDoc | Constants.FP_NextColorInDoc | Constants.FP_NextColumnInTbl |
	Constants.FP_NextCombinedFontDefnInDoc | Constants.FP_NextCommandInSession | Constants.FP_NextComponentInBook | Constants.FP_NextCondFmtInDoc | Constants.FP_NextDITAConrefElementInDoc | Constants.FP_NextDITALinkElementInDoc | Constants.FP_NextDITATopicrefElementInDoc | Constants.FP_NextDITATopicsetrefElementInDoc | Constants.FP_NextDITAXrefElementInDoc | Constants.FP_NextElementDFS |
	Constants.FP_NextElementDefInDoc | Constants.FP_NextFlowInDoc | Constants.FP_NextFmtChangeListInDoc | Constants.FP_NextFn | Constants.FP_NextFnInDoc | Constants.FP_NextGraphicInDoc | Constants.FP_NextGraphicInFrame | Constants.FP_NextGraphicInGroup | Constants.FP_NextGraphicsFmtInDoc | Constants.FP_NextInlineComponentInDoc |
	Constants.FP_NextInvalidElement | Constants.FP_NextKeyCatalogInSession | Constants.FP_NextMarkerInDoc | Constants.FP_NextMarkerTypeInDoc | Constants.FP_NextMenuItemInMenu | Constants.FP_NextMenuItemInSession | Constants.FP_NextOpenBookInSession | Constants.FP_NextOpenDocInSession | Constants.FP_NextPgfFmtInDoc | Constants.FP_NextPgfInDoc |
	Constants.FP_NextPgfInFlow | Constants.FP_NextRowInTbl | Constants.FP_NextRubiInDoc | Constants.FP_NextRulingFmtInDoc | Constants.FP_NextSelectedComponentInBook | Constants.FP_NextSelectedGraphicInDoc | Constants.FP_NextSiblingElement | Constants.FP_NextSubCol | Constants.FP_NextTag | Constants.FP_NextTblFmtInDoc |
	Constants.FP_NextTblInDoc | Constants.FP_NextTextFrameInFlow | Constants.FP_NextTiInDoc | Constants.FP_NextVarFmtInDoc | Constants.FP_NextVarInDoc | Constants.FP_NextVisibleColumnInTbl | Constants.FP_NextXRefFmtInDoc | Constants.FP_NextXRefInDoc | Constants.FP_No3DInPDF | Constants.FP_NoAppOutputPIFiltered |
	Constants.FP_NoFlashInPDF | Constants.FP_NoMultiMediaInPDF | Constants.FP_NotLoaded | Constants.FP_NumAtEnd | Constants.FP_NumCols | Constants.FP_NumColumns | Constants.FP_NumItems | Constants.FP_NumLines | Constants.FP_NumNamespaces | Constants.FP_NumPoints |
	Constants.FP_NumTabs | Constants.FP_Numbers | Constants.FP_Object | Constants.FP_ObjectAttributes | Constants.FP_ObjectFmtRules | Constants.FP_OldTypeNum | Constants.FP_OpenAndSaveXmlBookComponentDoc | Constants.FP_OpenDir | Constants.FP_OperatingSystem | Constants.FP_OptJLetSpace |
	Constants.FP_OptJRomSpace | Constants.FP_OptSpace | Constants.FP_OriginalDpi | Constants.FP_OriginalHeight | Constants.FP_OriginalWidth | Constants.FP_OrphanRows | Constants.FP_Outline | Constants.FP_Overflowed | Constants.FP_Overline | Constants.FP_Overprint |
	Constants.FP_OyamojiTextRange | Constants.FP_PDFAllNamedDestinations | Constants.FP_PDFBookmark | Constants.FP_PDFBookmarksOpenLevel | Constants.FP_PDFConvertCMYKtoRGB | Constants.FP_PDFDestsMarked | Constants.FP_PDFDistillerAbsent | Constants.FP_PDFDocInfo | Constants.FP_PDFEndPage | Constants.FP_PDFGenerateForReview |
	Constants.FP_PDFJobOption | Constants.FP_PDFJobOptions | Constants.FP_PDFJobOptionsAbsent | Constants.FP_PDFOpenPage | Constants.FP_PDFPageHeight | Constants.FP_PDFPageNum | Constants.FP_PDFPageWidth | Constants.FP_PDFPrintPageRange | Constants.FP_PDFRegistrationMarks | Constants.FP_PDFSeparateFiles |
	Constants.FP_PDFStartPage | Constants.FP_PDFStructure | Constants.FP_PDFStructureLevel | Constants.FP_PDFViewPDF | Constants.FP_PDFZoomFactor | Constants.FP_PDFZoomType | Constants.FP_PageBackground | Constants.FP_PageFrame | Constants.FP_PageFramePage | Constants.FP_PageHeight |
	Constants.FP_PageIsRecto | Constants.FP_PageNext | Constants.FP_PageNum | Constants.FP_PageNumComputeMethod | Constants.FP_PageNumString | Constants.FP_PageNumStyle | Constants.FP_PagePrefix | Constants.FP_PagePrev | Constants.FP_PageRounding | Constants.FP_PageSide |
	Constants.FP_PageSuffix | Constants.FP_PageWidth | Constants.FP_PairKern | Constants.FP_Pantone | Constants.FP_ParentElement | Constants.FP_ParentTextFrame | Constants.FP_ParseFullSpecification | Constants.FP_ParsedGeneralRule | Constants.FP_ParsedSpecification | Constants.FP_PasswordStyle |
	Constants.FP_Path | Constants.FP_Pen | Constants.FP_PercentDone | Constants.FP_PgfAlignment | Constants.FP_PgfBoxColor | Constants.FP_PgfCatalogReference | Constants.FP_PgfIsAutoNum | Constants.FP_PgfMarkedForNamedDestination | Constants.FP_PgfNumComputeMethod | Constants.FP_PgfNumber |
	Constants.FP_PgfSpacingFactor | Constants.FP_PgfSpellChecked | Constants.FP_PgfSplit | Constants.FP_Placement | Constants.FP_Platform | Constants.FP_PointPageNum | Constants.FP_PointPageNumStyle | Constants.FP_Points | Constants.FP_PolyIsBezier | Constants.FP_Position |
	Constants.FP_PrefixRules | Constants.FP_PreserveFormattingInXml | Constants.FP_PrevAFrame | Constants.FP_PrevBookComponentInDFSOrder | Constants.FP_PrevCell | Constants.FP_PrevCellInRow | Constants.FP_PrevColumnInTbl | Constants.FP_PrevComponentInBook | Constants.FP_PrevElementDFS | Constants.FP_PrevFn |
	Constants.FP_PrevGraphicInFrame | Constants.FP_PrevGraphicInGroup | Constants.FP_PrevMenuItemInMenu | Constants.FP_PrevPgfInFlow | Constants.FP_PrevRowInTbl | Constants.FP_PrevSiblingElement | Constants.FP_PrevSubCol | Constants.FP_PrevTextFrameInFlow | Constants.FP_PrevVisibleColumnInTbl | Constants.FP_PreviewState |
	Constants.FP_PrintBlankPages | Constants.FP_PrintCollated | Constants.FP_PrintCols | Constants.FP_PrintDitavalFileName | Constants.FP_PrintDownloadAsianFonts | Constants.FP_PrintDownloadTrueTypeAsType1 | Constants.FP_PrintEmulsion | Constants.FP_PrintEndPage | Constants.FP_PrintEndPageName | Constants.FP_PrintEndPoint |
	Constants.FP_PrintEvenPages | Constants.FP_PrintFileName | Constants.FP_PrintImaging | Constants.FP_PrintInclude | Constants.FP_PrintLastSheetFirst | Constants.FP_PrintLowRes | Constants.FP_PrintManualFeed | Constants.FP_PrintNumCopies | Constants.FP_PrintOddPages | Constants.FP_PrintPaperHeight |
	Constants.FP_PrintPaperWidth | Constants.FP_PrintRegMarkDate | Constants.FP_PrintRegistrationMarks | Constants.FP_PrintRows | Constants.FP_PrintScale | Constants.FP_PrintScope | Constants.FP_PrintSeps | Constants.FP_PrintSpotBW | Constants.FP_PrintStartPage | Constants.FP_PrintStartPageName |
	Constants.FP_PrintStartPoint | Constants.FP_PrintThumbnails | Constants.FP_PrintToFile | Constants.FP_PrintTomboMarks | Constants.FP_PrinterName | Constants.FP_ProcessNumber | Constants.FP_Product | Constants.FP_ProductFamily | Constants.FP_ProductIsDemo | Constants.FP_ProductIsStructured |
	Constants.FP_ProductName | Constants.FP_ProgId | Constants.FP_Public | Constants.FP_Radius | Constants.FP_RasterFilterDpi | Constants.FP_ReadOnly | Constants.FP_RectangleIsSmoothed | Constants.FP_Reformatting | Constants.FP_RememberMissingFontNames | Constants.FP_RemoveExtraWhiteSpacesOnXMLImport |
	Constants.FP_Required | Constants.FP_ReservedColor | Constants.FP_ResizeGripperBarVisibility | Constants.FP_ResizeGripperPos | Constants.FP_ResolvedDirection | Constants.FP_RestartFrameAlertRequired | Constants.FP_RetainUndoState | Constants.FP_ReviewTime | Constants.FP_ReviewerName | Constants.FP_ReviewerNameList |
	Constants.FP_RightColNum | Constants.FP_RightIndent | Constants.FP_RightIndentChange | Constants.FP_RightMargin | Constants.FP_RightMasterPage | Constants.FP_RowIsShown | Constants.FP_RowKeepWithNext | Constants.FP_RowKeepWithPrev | Constants.FP_RowMaxHeight | Constants.FP_RowMinHeight |
	Constants.FP_RowStart | Constants.FP_RowTbl | Constants.FP_RowType | Constants.FP_RpcProgramNumber | Constants.FP_RpcPropertyName | Constants.FP_RubiAlignAtLineBounds | Constants.FP_RubiElement | Constants.FP_RubiFixedSize | Constants.FP_RubiOverhang | Constants.FP_RubiSize |
	Constants.FP_RubiTextRange | Constants.FP_RuleClauseType | Constants.FP_RulingGap | Constants.FP_RulingLines | Constants.FP_RulingPenWidth | Constants.FP_RulingSep | Constants.FP_RunInSeparator | Constants.FP_Runaround | Constants.FP_RunaroundGap | Constants.FP_ScreenCaptureDocToFile |
	Constants.FP_ScreenHeight | Constants.FP_ScreenWidth | Constants.FP_ScreenX | Constants.FP_ScreenY | Constants.FP_SecNumComputeMethod | Constants.FP_SectionNumStyle | Constants.FP_SectionNumText | Constants.FP_SectionNumber | Constants.FP_SelectedRow | Constants.FP_SelectedRowId |
	Constants.FP_SelectedRowItems | Constants.FP_SelectedTbl | Constants.FP_Sensitivity | Constants.FP_SepOverride | Constants.FP_SeparateInclusions | Constants.FP_ServerState | Constants.FP_ServerUrl | Constants.FP_Shadow | Constants.FP_ShiftOrUnshiftCommand | Constants.FP_ShowAll |
	Constants.FP_ShowCondIndicators | Constants.FP_ShowElementDescriptiveNames | Constants.FP_SideHeadGap | Constants.FP_SideHeadPlacement | Constants.FP_SideHeadRoomInFlow | Constants.FP_SideHeadWidth | Constants.FP_SideOffset | Constants.FP_Size | Constants.FP_SkipBlankSeps | Constants.FP_SmallCapsSize |
	Constants.FP_SmallCapsStretch | Constants.FP_SmartQuotes | Constants.FP_SmartSpaces | Constants.FP_Snap | Constants.FP_SnapAngle | Constants.FP_SnapGridUnits | Constants.FP_SortingEnabled | Constants.FP_Source | Constants.FP_SourceType | Constants.FP_SpaceAbove |
	Constants.FP_SpaceAboveChange | Constants.FP_SpaceBelow | Constants.FP_SpaceBelowChange | Constants.FP_Spacing | Constants.FP_Specification | Constants.FP_SpecificationForCSS | Constants.FP_SpecifiedKeyCatalog | Constants.FP_SpotColorView | Constants.FP_Spread | Constants.FP_SpreadChange |
	Constants.FP_StackWarningLevel | Constants.FP_Start | Constants.FP_State | Constants.FP_StatusLine | Constants.FP_StopCountingAt | Constants.FP_Stretch | Constants.FP_StretchChange | Constants.FP_Strikethrough | Constants.FP_Strings | Constants.FP_StructAppAttrConfigFile |
	Constants.FP_StructAppsFile | Constants.FP_StructAppsFileId | Constants.FP_StructureCursorTypes | Constants.FP_StructuredApplication | Constants.FP_StructuredApplicationForOpen | Constants.FP_StructuredApplicationList | Constants.FP_StructuredDummyDocText | Constants.FP_StyleOverride | Constants.FP_StyleOverrides | Constants.FP_StyleTag |
	Constants.FP_SubFmtRule | Constants.FP_SubScriptShift | Constants.FP_SubScriptSize | Constants.FP_SubScriptStretch | Constants.FP_SubsecNumComputeMethod | Constants.FP_SubsectionNumStyle | Constants.FP_SubsectionNumText | Constants.FP_SubsectionNumber | Constants.FP_SuffixRules | Constants.FP_SuperScriptShift |
	Constants.FP_SuperScriptSize | Constants.FP_SuperScriptStretch | Constants.FP_SuppressXMLParserWarnings | Constants.FP_Symbols | Constants.FP_SymbolsList | Constants.FP_SystemVar | Constants.FP_TabStops | Constants.FP_TableTagging | Constants.FP_Tabs | Constants.FP_TailArrow |
	Constants.FP_TblAlignment | Constants.FP_TblBodyElement | Constants.FP_TblBodyFirstColor | Constants.FP_TblBodyFirstFill | Constants.FP_TblBodyFirstPeriod | Constants.FP_TblBodyNextColor | Constants.FP_TblBodyNextFill | Constants.FP_TblBodyNextPeriod | Constants.FP_TblBodyRowRuling | Constants.FP_TblBodyRowRulingPeriod |
	Constants.FP_TblBodyShadeBy | Constants.FP_TblBottomRuling | Constants.FP_TblCatalogEntry | Constants.FP_TblCellBottomMargin | Constants.FP_TblCellLeftMargin | Constants.FP_TblCellRightMargin | Constants.FP_TblCellTopMargin | Constants.FP_TblColRuling | Constants.FP_TblColRulingPeriod | Constants.FP_TblColWidths |
	Constants.FP_TblElement | Constants.FP_TblFnCellPosition | Constants.FP_TblFnCellPrefix | Constants.FP_TblFnCellSuffix | Constants.FP_TblFnCustNumString | Constants.FP_TblFnFmt | Constants.FP_TblFnNumComputeMethod | Constants.FP_TblFnNumStyle | Constants.FP_TblFnPosition | Constants.FP_TblFnPrefix |
	Constants.FP_TblFnSuffix | Constants.FP_TblFooterElement | Constants.FP_TblHFColor | Constants.FP_TblHFFill | Constants.FP_TblHFRowRuling | Constants.FP_TblHFSeparatorRuling | Constants.FP_TblHeaderElement | Constants.FP_TblInLockedTi | Constants.FP_TblInitNumBodyRows | Constants.FP_TblInitNumCols |
	Constants.FP_TblInitNumFRows | Constants.FP_TblInitNumHRows | Constants.FP_TblLastBodyRuling | Constants.FP_TblLeftIndent | Constants.FP_TblLeftRuling | Constants.FP_TblNumCols | Constants.FP_TblNumRows | Constants.FP_TblNumbering | Constants.FP_TblOtherBodyRowRuling | Constants.FP_TblOtherColRuling |
	Constants.FP_TblPlacement | Constants.FP_TblRightIndent | Constants.FP_TblRightRuling | Constants.FP_TblSpaceAbove | Constants.FP_TblSpaceBelow | Constants.FP_TblTag | Constants.FP_TblTitleElement | Constants.FP_TblTitleGap | Constants.FP_TblTitlePosition | Constants.FP_TblTitleSelected |
	Constants.FP_TblTopRuling | Constants.FP_TblWidth | Constants.FP_TechSuiteInternal | Constants.FP_TechSuiteInternal2 | Constants.FP_TemplateDatas | Constants.FP_Text | Constants.FP_TextColor | Constants.FP_TextFmtRules | Constants.FP_TextIsInvalidInElement | Constants.FP_TextLineType |
	Constants.FP_TextLoc | Constants.FP_TextRange | Constants.FP_TextSelection | Constants.FP_Theta | Constants.FP_TiAutomaticUpdate | Constants.FP_TiByRows | Constants.FP_TiClientData | Constants.FP_TiClientName | Constants.FP_TiClientSource | Constants.FP_TiClientType |
	Constants.FP_TiClientUpdateSilent | Constants.FP_TiEOLisEOP | Constants.FP_TiFile | Constants.FP_TiFileModDate | Constants.FP_TiFlowName | Constants.FP_TiFlowPageSpace | Constants.FP_TiFormat | Constants.FP_TiHeadersEmpty | Constants.FP_TiIsNested | Constants.FP_TiIsUnresolved |
	Constants.FP_TiLocked | Constants.FP_TiMacEdition | Constants.FP_TiMainFlow | Constants.FP_TiNumCols | Constants.FP_TiNumHeaderRows | Constants.FP_TiNumSeparators | Constants.FP_TiRemoveOverrides | Constants.FP_TiRemovePageBreaks | Constants.FP_TiSeparator | Constants.FP_TiTblTag |
	Constants.FP_TiTextEncoding | Constants.FP_TintBaseColor | Constants.FP_TintPercent | Constants.FP_TmpDir | Constants.FP_ToolBar | Constants.FP_ToolTipText | Constants.FP_TopMargin | Constants.FP_TopRowSelection | Constants.FP_TopSepAtIndent | Constants.FP_TopSeparator |
	Constants.FP_TopicRefAbsoluteFilePath | Constants.FP_TrackChangesAddedColor | Constants.FP_TrackChangesDeletedColor | Constants.FP_TrackChangesOn | Constants.FP_Transient | Constants.FP_TrapwiseCompatibility | Constants.FP_Tsume | Constants.FP_TypeOfDisplayText | Constants.FP_UIColorBackground | Constants.FP_UIColorRuler |
	Constants.FP_Underlining | Constants.FP_UndoFDKRecording | Constants.FP_Unique | Constants.FP_Untouchable | Constants.FP_UpdatingStructure | Constants.FP_UseAFrameIsCropped | Constants.FP_UseAFrameIsFloating | Constants.FP_UseAlignment | Constants.FP_UseAnchorType | Constants.FP_UseAngle |
	Constants.FP_UseBaselineOffset | Constants.FP_UseBkColor | Constants.FP_UseBorderWidth | Constants.FP_UseCapitalization | Constants.FP_UseChangeBar | Constants.FP_UseColGapWidth | Constants.FP_UseColor | Constants.FP_UseColumnsAreBalanced | Constants.FP_UseDTheta | Constants.FP_UseFMConsoleForErrorLog |
	Constants.FP_UseFill | Constants.FP_UseFlowIsAutoConnect | Constants.FP_UseFlowIsPostScript | Constants.FP_UseFontAngle | Constants.FP_UseFontFamily | Constants.FP_UseFontSize | Constants.FP_UseFontVariation | Constants.FP_UseFontWeight | Constants.FP_UseHeight | Constants.FP_UseInitialStructure |
	Constants.FP_UseInitialStructureOfAutoInsertedElements | Constants.FP_UseInsetDpi | Constants.FP_UseKernX | Constants.FP_UseKernY | Constants.FP_UseLanguage | Constants.FP_UseLocX | Constants.FP_UseLocY | Constants.FP_UseMathMLApplyPgfStyle | Constants.FP_UseMathMLComposeDpi | Constants.FP_UseMathMLDpi |
	Constants.FP_UseMathMLFontSize | Constants.FP_UseMathMLInline | Constants.FP_UseMathSize | Constants.FP_UseNextTag | Constants.FP_UseNumColumns | Constants.FP_UseOutline | Constants.FP_UseOverline | Constants.FP_UseOverprint | Constants.FP_UsePairKern | Constants.FP_UsePen |
	Constants.FP_UsePosition | Constants.FP_UseRadius | Constants.FP_UseRunaround | Constants.FP_UseRunaroundGap | Constants.FP_UseSepOverride | Constants.FP_UseShadow | Constants.FP_UseSideHeadGap | Constants.FP_UseSideHeadPlacement | Constants.FP_UseSideHeadWidth | Constants.FP_UseSideOffset |
	Constants.FP_UseSpread | Constants.FP_UseStretch | Constants.FP_UseStrikethrough | Constants.FP_UseTextLineType | Constants.FP_UseTheta | Constants.FP_UseTintPercent | Constants.FP_UseTsume | Constants.FP_UseUnderlining | Constants.FP_UseWidth | Constants.FP_UserHomeDir |
	Constants.FP_UserLogin | Constants.FP_UserName | Constants.FP_UserSettingsDir | Constants.FP_UserString | Constants.FP_ValidHighestLevel | Constants.FP_Validating | Constants.FP_ValidationFlags | Constants.FP_VarFmt | Constants.FP_Variables | Constants.FP_VersionDescription |
	Constants.FP_VersionMajor | Constants.FP_VersionMinor | Constants.FP_VersionRevision | Constants.FP_VerticalSpreadLarge | Constants.FP_VerticalSpreadMed | Constants.FP_VerticalSpreadSmall | Constants.FP_View | Constants.FP_ViewBorders | Constants.FP_ViewBreadCrumbs | Constants.FP_ViewDisplayUnits |
	Constants.FP_ViewFontSizeUnits | Constants.FP_ViewGrid | Constants.FP_ViewGridUnits | Constants.FP_ViewHotspotIndicators | Constants.FP_ViewLinkBoundaries | Constants.FP_ViewNoGraphics | Constants.FP_ViewOnlyDeadCodes | Constants.FP_ViewOnlyMenuBar | Constants.FP_ViewOnlySelect | Constants.FP_ViewOnlyWinBorders |
	Constants.FP_ViewOnlyWinMenubar | Constants.FP_ViewOnlyWinPalette | Constants.FP_ViewOnlyWinPopup | Constants.FP_ViewOnlyXRef | Constants.FP_ViewPageScrolling | Constants.FP_ViewRulerUnits | Constants.FP_ViewRulers | Constants.FP_ViewTextSymbols | Constants.FP_Visibility | Constants.FP_VisualCaretMovement |
	Constants.FP_VolNumComputeMethod | Constants.FP_VolumeNumStyle | Constants.FP_VolumeNumText | Constants.FP_VolumeNumber | Constants.FP_WesternFamily | Constants.FP_WesternFontPanoseName | Constants.FP_WesternFontPlatformName | Constants.FP_WesternFontPostScriptName | Constants.FP_WesternShift | Constants.FP_WesternSize |
	Constants.FP_WideRubiSpaceForJapanese | Constants.FP_WideRubiSpaceForOther | Constants.FP_Width | Constants.FP_Window | Constants.FP_WindowHandle | Constants.FP_WindowSystem | Constants.FP_XMLStructuredApplicationList | Constants.FP_XRefAltText | Constants.FP_XRefClientName | Constants.FP_XRefClientType |
	Constants.FP_XRefFile | Constants.FP_XRefFmt | Constants.FP_XRefIsUnresolved | Constants.FP_XRefResolvedWithKeyref | Constants.FP_XRefRetainKeydefText | Constants.FP_XRefSrcElemNonUniqueId | Constants.FP_XRefSrcIsElem | Constants.FP_XRefSrcText | Constants.FP_XSLTProcessors | Constants.FP_XSLTTransformationScenarioFile |
	Constants.FP_XmlApplicationForBookComponent | Constants.FP_XmlDocType | Constants.FP_XmlEncoding | Constants.FP_XmlFileEncoding | Constants.FP_XmlIsBook | Constants.FP_XmlLock | Constants.FP_XmlPublicId | Constants.FP_XmlStandAlone | Constants.FP_XmlStyleSheet | Constants.FP_XmlStyleSheetList |
	Constants.FP_XmlSystemId | Constants.FP_XmlUseBOM | Constants.FP_XmlVersion | Constants.FP_XmlWellFormed | Constants.FP_YakumonoType | Constants.FP_Year | Constants.FP_Yellow | Constants.FP_Zoom;

/** Types of alert dialog boxes. */
type FF_ALERT = Constants.FF_ALERT_OK_DEFAULT | Constants.FF_ALERT_CANCEL_DEFAULT | Constants.FF_ALERT_CONTINUE_NOTE | Constants.FF_ALERT_CONTINUE_WARN | Constants.FF_ALERT_YES_DEFAULT | Constants.FF_ALERT_NO_DEFAULT | Constants.FF_ALERT_YES_NO_CANCEL | Constants.FF_ALERT_DNS_OK;

/** Type property of a `Tab` object. */
type TabType = Constants.FV_TAB_LEFT | Constants.FV_TAB_CENTER | Constants.FV_TAB_RIGHT | Constants.FV_TAB_DECIMAL | Constants.FV_TAB_RELATIVE_LEFT | Constants.FV_TAB_RELATIVE_CENTER | Constants.FV_TAB_RELATIVE_RIGHT | Constants.FV_TAB_RELATIVE_DECIMAL;

/** Type property of `TypedVal` object. */
type TypedValType = Constants.FT_Integer | Constants.FT_Metric | Constants.FT_String | Constants.FT_Id | Constants.FT_Metrics | Constants.FT_Strings | Constants.FT_Points | Constants.FT_Tabs | Constants.FT_TextLoc | Constants.FT_TextRange | Constants.FT_ElementCatalog | Constants.FT_Ints | Constants.FT_UBytes | Constants.FT_UInts | Constants.FT_AttributeDefs | Constants.FT_Attributes;