// Type definitions for composite types and helper interfaces
// Definitions by Dan Reed <https://danreed.dev>

/** @todo Complete this list. Any FrameMaker object. */
type FMObject = null;

/** @todo Complete this list. Any FrameMaker graphic object. */
type FMGraphic = null;

/** Constants that represent FMObject types. */
type FO_Constant = Constants.FO_Session | Constants.FO_StringResource | Constants.FO_Book | Constants.FO_BookComponent | Constants.FO_Doc | Constants.FO_BodyPage | Constants.FO_MasterPage | Constants.FO_RefPage | Constants.FO_HiddenPage | Constants.FO_UnanchoredFrame | Constants.FO_Group | Constants.FO_Arc | Constants.FO_Rectangle | Constants.FO_Ellipse | Constants.FO_RoundRect | Constants.FO_Polyline | Constants.FO_Polygon | Constants.FO_Line | Constants.FO_TextLine | Constants.FO_TextFrame | Constants.FO_Inset | Constants.FO_Math | Constants.FO_DBGroup | Constants.FO_AFrame | Constants.FO_Marker | Constants.FO_Fn | Constants.FO_XRef | Constants.FO_XRefFmt | Constants.FO_Var | Constants.FO_VarFmt | Constants.FO_Flow | Constants.FO_Pgf | Constants.FO_PgfFmt | Constants.FO_CharFmt | Constants.FO_CondFmt | Constants.FO_Color | Constants.FO_Tbl | Constants.FO_TblFmt | Constants.FO_Row | Constants.FO_Cell | Constants.FO_RulingFmt | Constants.FO_ElementDef | Constants.FO_Element | Constants.FO_DialogResource | Constants.FO_DlgBox | Constants.FO_DlgButton | Constants.FO_DlgTriBox | Constants.FO_DlgCheckBox | Constants.FO_DlgPopUp | Constants.FO_DlgScrollBox | Constants.FO_DlgEditBox | Constants.FO_DlgRadioButton | Constants.FO_DlgLabel | Constants.FO_DlgImage | Constants.FO_DlgScrollBar | Constants.FO_Menu | Constants.FO_Command | Constants.FO_MenuItemSeparator | Constants.FO_FmtChangeList | Constants.FO_FmtRule | Constants.FO_FmtRuleClause | Constants.FO_TiFlow | Constants.FO_TiText | Constants.FO_TiTextTable | Constants.FO_TiApiClient | Constants.FO_SubCol | Constants.FO_MarkerType | Constants.FO_CombinedFontDefn | Constants.FO_Rubi | Constants.FO_Alert | Constants.FO_CursorResource | Constants.FO_AttrCondExpr | Constants.FO_DlgListView | Constants.FO_GraphicsFmt | Constants.FO_CMSRegistration | Constants.FO_CMSSession | Constants.FO_CMSObject | Constants.FO_KeyCatalog | Constants.FO_Iterator | Constants.FO_MathML | Constants.FO_DlgDate | Constants.FO_InlineComponent | Constants.FO_Column | Constants.FO_Page | Constants.FO_Graphic | Constants.FO_Frame | Constants.FO_Cblock | Constants.FO_SubCond | Constants.FO_SubStyle | Constants.FO_SubDash | Constants.FO_SubCell | Constants.FO_SubTbl | Constants.FO_SubPblock | Constants.FO_SubTextDef | Constants.FO_MenuCell | Constants.FO_TextInset | Constants.FO_DitaMap | Constants.FO_Last_Internal | Constants.FO_CMSConnection | Constants.FO_CMSObject2 | Constants.FO_Bad;

/** Types of alert dialog boxes. */
type FF_ALERT = Constants.FF_ALERT_OK_DEFAULT | Constants.FF_ALERT_CANCEL_DEFAULT | Constants.FF_ALERT_CONTINUE_NOTE | Constants.FF_ALERT_CONTINUE_WARN | Constants.FF_ALERT_YES_DEFAULT | Constants.FF_ALERT_NO_DEFAULT | Constants.FF_ALERT_YES_NO_CANCEL | Constants.FF_ALERT_DNS_OK;